name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        run: npm install -g pnpm@7

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests and build
        run: pnpm run ci

      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
